CREATE TABLE rental
(
    "RENTAL_ID" NUMBER(10,0), 
	"RENTAL_DATE" TIMESTAMP (6), 
	"INVENTORY_ID" NUMBER(10,0), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"RETURN_DATE" TIMESTAMP (6), 
	"STAFF_ID" NUMBER(5,0), 
	"LAST_UPDATE" TIMESTAMP (6)
);
